DROP TABLE IF EXISTS TBL_TWITER;
 
CREATE TABLE TBL_TWITER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  usuario VARCHAR(250) NOT NULL,
  texto VARCHAR(350) NOT NULL,
  localizacion VARCHAR(250) NOT NULL,
  validacion NUMBER(1) NOT NULL
);